language: node_js
sudo: false
node_js:
  - 6
before_install: npm install -g npm@'>=2.13.5'
before_script:
- npm rebuild
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#payments
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: payments-devs-automation+npm@mozilla.com
  skip_cleanup: true
  api_key:
    secure: ABfJ/S0FzKgB2erhLqRPYJQFfBcZNe1dQTcyxQZWgo9E17Xv9cxS8Ca61y45TRcUsUcadUbBharErnx2WWjlSs5Q0H3QxF+taExIpya8BuzFZVIha/tNUu3eM98HoDbIyLPwJdSQUq9WV1LigWAUXZIv0rM4tqRj9/fhzf5PQg3Dvhf/k8swUoiS30zG4kGMFRxtQQ2RyaOXdhHYK1kquCWos4xbpIILerKMV8iDLKOqwakEf5j5uSWd1F15iRDmpjz2jnlgi6wBLFJDBxO7M5VBP/lS8U7EuTJ8sSB79NN5ck5mKzQDMKb04Km4GUZj0m5IbJbBY9Os9Z2qv49Y797sbrTEpWgjxIGy2XgThE7TVDv3lCwrGC9GVUYgseKDvl5C1Vd5mTlioWluBCpS7vNl94FaAzJxEPITNLDsd58ntIQrXkfU41tY4kBmgsep7Cj+FBoRGHVPRnc8x6Lzc7moVr2dSToTXLv8y2xnwXP4sp/N53amU4e3wRf1lzV/RnXEc4QgMEEl9ZK6f84oGPpqOLYE5u5buErbkk1KyBKxuDb5SKpuMVu4rPLt/vbGEV+mC8wckdOHK93H2OOFGPM8F8FzENesgW+CnJc1w5eWxJdwFxzgAo/hdB5sUSY80SyVdMpkx0MQlj66MrGNDt26Sk9Xtc7aPEf9llQkO9Y=
  on:
    tags: true
    repo: mozilla/payments-client
env:
  global:
  - secure: rBbGQ/SXrTg6hiYsl/tuIeszJe9bMwhmuQPDSuHlZ4zBnLeM1WVGvl4iLQ909OSc3XCjEqXEJatl64yPFdM3bVYMPAdnJg1mlzpF5MVQ7EB/hdvpuV/ghHI7BO4QPOR7G7ERZdK1cLDJALFpAXPyRaoYEmAHS//4Ex7EpEe+MBiurop4NJriXPH7++uOHTPzJE6VKm1S0tbZgjPX97FYsPa/urlT3DYT4b4EP0QNf1oUVQzYIRNnPTb58dNq06MoSMhVS4q2n3PKPLB1KTqcBSl3cIFXlWSsajBmYulh+uN9fpheiEN3vA55SAWcLvfFOO/6w8WHxtd8Pl0wYKV1HpRmU2V8WHcp/0N7mS8b9uPmQ0dLLwuupHRobPHJ4fyHUG4vGmby1em9EAvbPphYxf02QdezOSETbee+3CA7ypszYosz9uRKLVaB6/DYNbjZ1Vw9S2lPJAeBQ82iYVtgDHFQDsM6JuOlDh3nv/oy6ro25mAAa2bEFKnaIL0IYvN9rPI/JwRL3O2Q1mXL3EXoHBZz8zXmfaPK/c3dmreBSke/Y8tfHSM7QOw0OTeQuPutAX8rmOdilpBSKnF/RzaPuaVwFzOxYXco3nwMKw4ikoDORjvS8fhfMaShcaKxC4Be16CwZn/iXWJ/l2egGqeEbawUsRVQj/x7a1t1UoWNVso=
  - secure: uwP4djcQZg3NlDZUCctpfWrS7DHqc0pJ3TVETHvH1/mWbkNagFJYV86zOmc3YP8mDg+I2VvKjDw7/ZwNV+sY15NXOnIhSuFjPv+1AazCoaGo0CMTHKshw3Q3XnpnPkv19LdyCSBI5AKVxCt3mac7M6oQGfyGkTbLJXc+rO8DacAnmH2APousrBG5ERwR/+Kf2TGdsT5ld60t8eo9grYDL03xuqaLUM10z/CBM2E8GgMwny97ZoCs3cdG5EvanmJJbxLSbWwx2zvYrkUeuymXbqAPxUtgkDsxDKwZIy2/+U/gWfpPFClsrtVNPI+WwaotvZ68barLGdVKW6ZDg1FlJCUE8+Tv7yYD0CtmRrO28+xtnPFtCUTKNytrX4OTs5HYYSad9F9E5F1k3UntnvSukpjjAsNcqfvg3ZQe6CiINKRthR8u/N5RK/cNaZaG67zD7cn3R/Zn/V2VJ0OUUl2DTezPnaflctaQKqn13t1JQ/3GiE6GPKtcrRYr0NIGWstJl5QbRFp6Ta7E01suzKlTKgoQlNNlh+4uiq3wEWOl2bPNLMyMgJB96w/6+QuKwYME9wvl4ZSDKcYY3QWIhrsVUJNtNfaUYhqHAwpkB0ifOH+HY84wes2WcK93xxTmDoB6SbQvVLTiG5qDU0B/3MEZmLcgDI5/r7/Yd8pVPMQfvzY=
